language: php

env:
  - NETTE=default
  - NETTE=~2.4.0

php:
  - 7.1
  - 7.2

before_install:
  - composer self-update

before_script:
  - php .travis.composer.php
  - composer install --no-interaction --prefer-source --dev

script:
  - vendor/bin/tester -s -p php -c ./tests/php.ini-unix tests

after_failure:
  - 'for i in $(find ./tests -name \*.actual); do echo "--- $i"; cat $i; echo; echo; done'
